export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECT_ARTICLES = 'SELECT_ARTICLES'

export const SELECT_RANGE = 'SELECT_RANGE'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
